; Global settings for redshift
[redshift]
; Set the day and night screen temperatures
temp-day=6500
temp-night=2000

; Disable the smooth fade between temperatures when Redshift starts and stops.
fade=0

; Custom dawn/dusk intervals.
dawn-time=4:00-6:15
dusk-time=20:35-23:59

; Set the screen brightness. Default is 1.0.
brightness-day=1
brightness-night=0.9

; Set the screen gamma
gamma=1

; Set the location-provider: 'geoclue2', 'manual'
location-provider=manual

; Set the adjustment-method: 'randr', 'vidmode'
adjustment-method=randr

; Configuration of the location-provider:
[manual]
lat=38.9
lon=-77.0

; Configuration of the adjustment-method
[randr]
